/**
 * Pulls real public repository data from the GitHub API into data/github.json.
 *
 *   npm run sync:github
 *
 * This replaced a third-party stats card. Two reasons, both worth keeping in
 * mind before anyone adds one back:
 *
 *   1. Those cards lead with stars, pull requests and issues. For a developer
 *      whose work is client sites and private tooling, that is a row of zeros —
 *      a true number that tells a lie about the work.
 *   2. They are someone else's uptime, someone else's rate limit, and someone
 *      else's visual language on your profile.
 *
 * What is rendered instead is language distribution measured in bytes across
 * the public repositories, plus an index of what is actually there. Both are
 * facts, both auto-update, and both are drawn in this profile's own system.
 *
 * Runs unauthenticated (60 requests/hour, and this needs about ten) or with
 * GITHUB_TOKEN set, which CI provides.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const profile = JSON.parse(fs.readFileSync(path.join(root, "data", "profile.json"), "utf8"));
const user = profile.links.github.split("/").pop();

/**
 * Repositories that exist but say nothing about the work. Curation, not
 * concealment — each one is listed with the reason it is out.
 */
const EXCLUDE = {
  [user]: "this repository — the profile itself",
  "code-tracking": "auto-generated, empty",
};

const headers = {
  Accept: "application/vnd.github+json",
  "User-Agent": `${user}-profile-build`,
  ...(process.env.GITHUB_TOKEN ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
};

async function api(url) {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  return res.json();
}

const all = await api(`https://api.github.com/users/${user}/repos?per_page=100&sort=pushed`);

const repos = [];
const bytes = new Map();

for (const r of all) {
  if (r.fork || r.private || EXCLUDE[r.name]) continue;

  // Language bytes are the honest measure of what someone actually writes —
  // a repo's single "language" field hides everything else in it.
  let langs = {};
  try {
    langs = await api(r.languages_url);
  } catch (e) {
    console.warn(`  ! languages unavailable for ${r.name}: ${e.message}`);
  }
  for (const [name, n] of Object.entries(langs)) bytes.set(name, (bytes.get(name) || 0) + n);

  repos.push({
    name: r.name,
    description: r.description,
    language: r.language,
    homepage: r.homepage || null,
    url: r.html_url,
    pushedAt: r.pushed_at,
    stars: r.stargazers_count,
  });
}

const total = [...bytes.values()].reduce((a, b) => a + b, 0);
const languages = [...bytes.entries()]
  .sort((a, b) => b[1] - a[1])
  .map(([name, n]) => ({ name, bytes: n, share: Math.round((n / total) * 1000) / 10 }))
  .filter((l) => l.share >= 1);

const out = {
  $comment:
    "Generated by `npm run sync:github` from the public GitHub API. Do not hand-edit — rerun it instead. Excluded repositories and why: " +
    Object.entries(EXCLUDE).map(([k, v]) => `${k} (${v})`).join("; ") + ".",
  fetchedAt: new Date().toISOString(),
  user,
  repoCount: repos.length,
  lastPush: repos.map((r) => r.pushedAt).sort().pop() || null,
  languages,
  repos,
};

fs.writeFileSync(path.join(root, "data", "github.json"), JSON.stringify(out, null, 2) + "\n");

console.log(`\n${repos.length} public repositories · ${(total / 1024).toFixed(0)} kB of source\n`);
for (const l of languages) console.log(`  ${l.name.padEnd(14)} ${String(l.share).padStart(5)}%`);
console.log(`\nwritten to data/github.json — run \`npm run build\` to render it\n`);
